# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

sass:
    sass_dir: assets/css/

beispiele:
  - title: CAVIC2
    file: CAVIC2.smt
  - title: CircularRebars
    file: CircularRebars.smt
  - title: CoordArrows
    file: CoordArrows.smt
  - title: Curved3DText
    file: Curved3DText.smt
  - title: CurvedText
    file: CurvedText.smt
  - title: Curve_N2
    file: Curve_N2.smt
  - title: dowels
    file: dowels.smt
  - title: dowels2
    file: dowels2.smt
  - title: Fertigteilabdeckung
    file: Fertigteilabdeckung.smt
  - title: HE-A
    file: HE-A.smt
  - title: HE-B
    file: HE-B.smt
  - title: HE-M
    file: HE-M.smt
  - title: I-Reihe
    file: I-Reihe.smt
  - title: I
    file: I.smt
  - title: IPE
    file: IPE.smt
  - title: Klothoide
    file: Klothoide.smt
  - title: Köcherfundament
    file: Köcherfundament.smt
  - title: ÖBB Geländer 1
    file: oebb-railing-1.smt
  - title: ÖBB Geländer 2
    file: oebb-railing-2.smt
  - title: ÖBB Geländer 3
    file: oebb-railing-3.smt
  - title: ÖBB Geländer 4
    file: oebb-railing-4.smt
  - title: PlayGround
    file: PlayGround.smt
  - title: PlayGround2D
    file: PlayGround2D.smt
  - title: RangingRebars
    file: RangingRebars.smt
  - title: Spline2
    file: Spline2.smt
  - title: SplineRebars
    file: SplineRebars.smt
  - title: Waterstop Corner
    file: waterstop-corner.smt
  - title: Waterstop Parallel Shift
    file: waterstop-parallel-shift.smt
  - title: Waterstop Straight
    file: waterstop-straight.smt

nav:
  - title: Willkommen
    url: /
  - title: BASIC Referenz
    url: /basic-referenz.html
    app: /assets/img/basic.jpg
    subnav:
    - title: Funktionen
      url: /basic-referenz/funktionen.html
    - title: Globale Variablen
      url: /basic-referenz/globale-variablen.html
    - title: Parameter-Buffer
      url: /basic-referenz/parameter-stack.html
    - title: Schleifen
      url: /basic-referenz/Schleifen.html
    - title: Sonstige Kontrollbefehle
      url: /basic-referenz/sonstige-kontrollbefehle.html
    - title: Variablen
      url: /basic-referenz/variablen.html
    - title: Vergleichsoperatoren
      url: /basic-referenz/vergleichsoperatoren.html
    - title: Verzweigungen
      url: /basic-referenz/verzweigungen.html
  - title: 2D Scripting
    url: /2d-scripting.html
    app: /assets/img/2D Script.jpg
    subnav:
    - title: Grundformen
      url: "/2d-scripting/grundformen.html"
    - title: Kurven
      url: "/2d-scripting/curves.html"
    - title: Pixelbilder
      url: "/2d-scripting/rect_pict2.html"
    - title: Polygone
      url: "/2d-scripting/poly2.html"
  - title: 3D Scripting
    url: "/3d-scripting.html"
    app: /assets/img/3D Script.jpg
    subnav:
    - title: Einfache Volumenkörper
      url: "/3d-scripting/einfache-volumenkoerper.html"
    - title: Flächen und Linien
      url: "/3d-scripting/flaechen-und-linien.html"
    - title: Gruppen
      url: "/3d-scripting/gruppen.html"
    - title: Schnittoperationen
      url: "/3d-scripting/Schnittoperationen.html"
    - title: Oberflächen und Körper aus Polygonen
      url: "/3d-scripting/oberflaechen-aus-polygonen.html"
    - title: Prismen
      url: "/3d-scripting/prismen.html"
  - title: Bewehrung
    url: "/bewehrung.html"
    app: /assets/img/Bewehrung.jpg
    subnav:
    - title: Biegeform
      url: "/bewehrung/biegeform.html"
    - title: Verlegung
      url: "/bewehrung/verlegung.html"
  - title: Transformationen
    url: "/transformationen.html"
    app: /assets/img/Transformationen.jpg
  - title: Parameter
    url: "/parameter.html"
    app: /assets/img/Parameter.jpg
  - title: Handles
    url: "/handles.html"
    app: /assets/img/Handles.jpg
  - title: Definitionen
    url: "/definitionen.html"
    app: /assets/img/Definitionen.jpg
    subnav:
    - title: BITMAP - Pixelfläche
      url: "/definitionen/bitmap.html"
    - title: FACE_STYLE
      url: "/definitionen/face_style.html"
    - title: FILL - Füllfarbe
      url: "/definitionen/fill.html"
    - title: FOIL - Folien
      url: "/definitionen/foil.html"
    - title: HATCHING - Schraffuren
      url: "/definitionen/hatching.html"
    - title: MATERIAL
      url: "/definitionen/material.html"
    - title: PATTER_LINE - Musterlinien
      url: "/definitionen/patter_line.html"
    - title: PATTERN - Musterflächen
      url: "/definitionen/pattern.html"
    - title: STYLE - Textstil
      url: "/definitionen/style.html"
    - title: TEXTURE
      url: "/definitionen/texture.html"
  - title: Objekteigenschaften
    url: "/objekteigenschaften.html"
    app: /assets/img/Objekteigenschaften.jpg
  - title: Statuscodes
    url: "/statuscodes.html"
    app: /assets/img/Statuscodes.jpg
  - title: Eingabepalette
    url: "/palette.html"
    app: /assets/img/Eingabepalette.jpg
  - title: Ressourcen
    url: "/ressourcen.html"
    app: /assets/img/Ressourcen.jpg
  - title: Dateibefehle
    url: "/dateibefehle.html"
    app: /assets/img/Dateibefehle.jpg
  - title: Beispiele
    url: "/beispiele/index.html"
    app: /assets/img/Dateibefehle.jpg

